// ****************************************************************************************************************************************
// Project          : Navyblue.BaseLibrary
// File             : Event.cs
// Created          : 2026-07-10  17:07
// 
// Last Modified By : kitt-nostalgic(jstsmaxx@gmail.com)
// Last Modified On : 2026-07-10  19:06
// ****************************************************************************************************************************************
// <copyright file="Event.cs" company="">
//     Copyright ©  2011-2026. All rights reserved.
// </copyright>
// ****************************************************************************************************************************************

namespace Navyblue.Foundation.Cqrs;

/// <summary>
///     Base representation for an Event
/// </summary>
/// <seealso cref="Navyblue.Foundation.Cqrs.IRequest" />
public abstract class Event : IRequest
{
    /// <summary>
    ///     Gets or sets the correlation identifier.
    /// </summary>
    /// <value>
    ///     The correlation identifier.
    /// </value>
    public string CorrelationId { get; set; }

    /// <summary>
    ///     Gets or sets the transaction identifier.
    /// </summary>
    /// <value>
    ///     The transaction identifier.
    /// </value>
    public string TransactionId { get; set; }

    /// <summary>
    ///     Gets or sets the generated by.
    /// </summary>
    /// <value>
    ///     The generated by.
    /// </value>
    public string GeneratedBy { get; set; }

    /// <summary>
    ///     Gets or sets the generated on.
    /// </summary>
    /// <value>
    ///     The generated on.
    /// </value>
    public DateTime GeneratedOn { get; set; }

    /// <summary>
    ///     Gets or sets the version.
    /// </summary>
    /// <value>
    ///     The version.
    /// </value>
    public string Version { get; set; }

    #region IRequest Members

    /// <summary>
    ///     Gets the display name.
    /// </summary>
    /// <value>
    ///     The display name.
    /// </value>
    public abstract string DisplayName { get; }

    /// <summary>
    ///     Gets or sets the identifier.
    /// </summary>
    /// <value>
    ///     The identifier.
    /// </value>
    public abstract string Id { get; set; }

    /// <summary>
    ///     Validates an event.
    /// </summary>
    /// <param name="validationErrorMessage">Error Message, if any</param>
    /// <returns>
    ///     True - If event is valid
    /// </returns>
    /// <remarks>
    ///     Ideally therey is no need for events to have a validation
    /// </remarks>
    public virtual bool Validate(out string validationErrorMessage)
    {
        // Events in general doesn't need to be validated
        validationErrorMessage = null;
        return true;
    }

    #endregion
}